name: MonthPlugin
version: 1.0.0
api-version: 1.12

author: Month

main: Month.Main.MonthPlugin

description:

commands:
  Month:
    description: Month
    aliases: mh
    permission: <plugin name>.Month
    permission-message: <permission>
permissions:
